import vm from "node:vm"
import yaml from "js-yaml"
import type { ParsedFile } from "./types.js"

function parseFrontmatter(content: string): ParsedFile | null {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/s)
  if (!match) return null

  const yamlStr = match[1] ?? ""
  const body = match[2] ?? ""

  try {
    const fields = yaml.load(yamlStr)
    if (!fields || typeof fields !== "object" || Array.isArray(fields)) return null
    return { format: "frontmatter", fields: fields as Record<string, unknown>, body }
  } catch {
    return null
  }
}

function extractObjectLiteral(content: string): { obj: string; rest: string } | null {
  const idx = content.indexOf("export const metadata")
  if (idx === -1) return null

  const braceStart = content.indexOf("{", idx)
  if (braceStart === -1) return null

  let depth = 0
  let end = -1

  for (let i = braceStart; i < content.length; i++) {
    const ch = content[i]
    if (ch === "{") depth++
    else if (ch === "}") {
      depth--
      if (depth === 0) {
        end = i + 1
        break
      }
    }
  }

  if (end === -1) return null

  const obj = content.slice(braceStart, end)
  const rest = content.slice(end).replace(/^\s*\n/, "")
  return { obj, rest }
}

function parseMetadataExport(content: string): ParsedFile | null {
  const extracted = extractObjectLiteral(content)
  if (!extracted) return null

  const { obj, rest } = extracted

  try {
    // Safe-ish: files are generated by this tool, format is controlled.
    // Date is injected so `new Date(...)` expressions resolve correctly.
    const ctx = vm.createContext({ Date, result: undefined as unknown })
    vm.runInContext(`result = ${obj}`, ctx)
    const fields = ctx.result
    if (!fields || typeof fields !== "object" || Array.isArray(fields)) return null
    return {
      format: "metadata-export",
      fields: fields as Record<string, unknown>,
      body: rest,
    }
  } catch {
    return null
  }
}

export function parseFile(content: string): ParsedFile | null {
  if (content.startsWith("---")) return parseFrontmatter(content)
  if (content.includes("export const metadata")) return parseMetadataExport(content)
  return null
}
